// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/signingcommitment"
)

// SigningCommitmentQuery is the builder for querying SigningCommitment entities.
type SigningCommitmentQuery struct {
	config
	ctx        *QueryContext
	order      []signingcommitment.OrderOption
	inters     []Interceptor
	predicates []predicate.SigningCommitment
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SigningCommitmentQuery builder.
func (scq *SigningCommitmentQuery) Where(ps ...predicate.SigningCommitment) *SigningCommitmentQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit the number of records to be returned by this query.
func (scq *SigningCommitmentQuery) Limit(limit int) *SigningCommitmentQuery {
	scq.ctx.Limit = &limit
	return scq
}

// Offset to start from.
func (scq *SigningCommitmentQuery) Offset(offset int) *SigningCommitmentQuery {
	scq.ctx.Offset = &offset
	return scq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scq *SigningCommitmentQuery) Unique(unique bool) *SigningCommitmentQuery {
	scq.ctx.Unique = &unique
	return scq
}

// Order specifies how the records should be ordered.
func (scq *SigningCommitmentQuery) Order(o ...signingcommitment.OrderOption) *SigningCommitmentQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// First returns the first SigningCommitment entity from the query.
// Returns a *NotFoundError when no SigningCommitment was found.
func (scq *SigningCommitmentQuery) First(ctx context.Context) (*SigningCommitment, error) {
	nodes, err := scq.Limit(1).All(setContextOp(ctx, scq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{signingcommitment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *SigningCommitmentQuery) FirstX(ctx context.Context) *SigningCommitment {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SigningCommitment ID from the query.
// Returns a *NotFoundError when no SigningCommitment ID was found.
func (scq *SigningCommitmentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scq.Limit(1).IDs(setContextOp(ctx, scq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{signingcommitment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *SigningCommitmentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SigningCommitment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SigningCommitment entity is found.
// Returns a *NotFoundError when no SigningCommitment entities are found.
func (scq *SigningCommitmentQuery) Only(ctx context.Context) (*SigningCommitment, error) {
	nodes, err := scq.Limit(2).All(setContextOp(ctx, scq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{signingcommitment.Label}
	default:
		return nil, &NotSingularError{signingcommitment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *SigningCommitmentQuery) OnlyX(ctx context.Context) *SigningCommitment {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SigningCommitment ID in the query.
// Returns a *NotSingularError when more than one SigningCommitment ID is found.
// Returns a *NotFoundError when no entities are found.
func (scq *SigningCommitmentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scq.Limit(2).IDs(setContextOp(ctx, scq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{signingcommitment.Label}
	default:
		err = &NotSingularError{signingcommitment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *SigningCommitmentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SigningCommitments.
func (scq *SigningCommitmentQuery) All(ctx context.Context) ([]*SigningCommitment, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryAll)
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SigningCommitment, *SigningCommitmentQuery]()
	return withInterceptors[[]*SigningCommitment](ctx, scq, qr, scq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scq *SigningCommitmentQuery) AllX(ctx context.Context) []*SigningCommitment {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SigningCommitment IDs.
func (scq *SigningCommitmentQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if scq.ctx.Unique == nil && scq.path != nil {
		scq.Unique(true)
	}
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryIDs)
	if err = scq.Select(signingcommitment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *SigningCommitmentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *SigningCommitmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryCount)
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scq, querierCount[*SigningCommitmentQuery](), scq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scq *SigningCommitmentQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *SigningCommitmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryExist)
	switch _, err := scq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *SigningCommitmentQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SigningCommitmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *SigningCommitmentQuery) Clone() *SigningCommitmentQuery {
	if scq == nil {
		return nil
	}
	return &SigningCommitmentQuery{
		config:     scq.config,
		ctx:        scq.ctx.Clone(),
		order:      append([]signingcommitment.OrderOption{}, scq.order...),
		inters:     append([]Interceptor{}, scq.inters...),
		predicates: append([]predicate.SigningCommitment{}, scq.predicates...),
		// clone intermediate query.
		sql:       scq.sql.Clone(),
		path:      scq.path,
		modifiers: append([]func(*sql.Selector){}, scq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SigningCommitment.Query().
//		GroupBy(signingcommitment.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (scq *SigningCommitmentQuery) GroupBy(field string, fields ...string) *SigningCommitmentGroupBy {
	scq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SigningCommitmentGroupBy{build: scq}
	grbuild.flds = &scq.ctx.Fields
	grbuild.label = signingcommitment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.SigningCommitment.Query().
//		Select(signingcommitment.FieldCreateTime).
//		Scan(ctx, &v)
func (scq *SigningCommitmentQuery) Select(fields ...string) *SigningCommitmentSelect {
	scq.ctx.Fields = append(scq.ctx.Fields, fields...)
	sbuild := &SigningCommitmentSelect{SigningCommitmentQuery: scq}
	sbuild.label = signingcommitment.Label
	sbuild.flds, sbuild.scan = &scq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SigningCommitmentSelect configured with the given aggregations.
func (scq *SigningCommitmentQuery) Aggregate(fns ...AggregateFunc) *SigningCommitmentSelect {
	return scq.Select().Aggregate(fns...)
}

func (scq *SigningCommitmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scq); err != nil {
				return err
			}
		}
	}
	for _, f := range scq.ctx.Fields {
		if !signingcommitment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *SigningCommitmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SigningCommitment, error) {
	var (
		nodes = []*SigningCommitment{}
		_spec = scq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SigningCommitment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SigningCommitment{config: scq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(scq.modifiers) > 0 {
		_spec.Modifiers = scq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (scq *SigningCommitmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	if len(scq.modifiers) > 0 {
		_spec.Modifiers = scq.modifiers
	}
	_spec.Node.Columns = scq.ctx.Fields
	if len(scq.ctx.Fields) > 0 {
		_spec.Unique = scq.ctx.Unique != nil && *scq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *SigningCommitmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(signingcommitment.Table, signingcommitment.Columns, sqlgraph.NewFieldSpec(signingcommitment.FieldID, field.TypeUUID))
	_spec.From = scq.sql
	if unique := scq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scq.path != nil {
		_spec.Unique = true
	}
	if fields := scq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signingcommitment.FieldID)
		for i := range fields {
			if fields[i] != signingcommitment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scq *SigningCommitmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(signingcommitment.Table)
	columns := scq.ctx.Fields
	if len(columns) == 0 {
		columns = signingcommitment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scq.ctx.Unique != nil && *scq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range scq.modifiers {
		m(selector)
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector)
	}
	if offset := scq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (scq *SigningCommitmentQuery) ForUpdate(opts ...sql.LockOption) *SigningCommitmentQuery {
	if scq.driver.Dialect() == dialect.Postgres {
		scq.Unique(false)
	}
	scq.modifiers = append(scq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return scq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (scq *SigningCommitmentQuery) ForShare(opts ...sql.LockOption) *SigningCommitmentQuery {
	if scq.driver.Dialect() == dialect.Postgres {
		scq.Unique(false)
	}
	scq.modifiers = append(scq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return scq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (scq *SigningCommitmentQuery) Modify(modifiers ...func(s *sql.Selector)) *SigningCommitmentSelect {
	scq.modifiers = append(scq.modifiers, modifiers...)
	return scq.Select()
}

// SigningCommitmentGroupBy is the group-by builder for SigningCommitment entities.
type SigningCommitmentGroupBy struct {
	selector
	build *SigningCommitmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *SigningCommitmentGroupBy) Aggregate(fns ...AggregateFunc) *SigningCommitmentGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the selector query and scans the result into the given value.
func (scgb *SigningCommitmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scgb.build.ctx, ent.OpQueryGroupBy)
	if err := scgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SigningCommitmentQuery, *SigningCommitmentGroupBy](ctx, scgb.build, scgb, scgb.build.inters, v)
}

func (scgb *SigningCommitmentGroupBy) sqlScan(ctx context.Context, root *SigningCommitmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scgb.fns))
	for _, fn := range scgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scgb.flds)+len(scgb.fns))
		for _, f := range *scgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SigningCommitmentSelect is the builder for selecting fields of SigningCommitment entities.
type SigningCommitmentSelect struct {
	*SigningCommitmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scs *SigningCommitmentSelect) Aggregate(fns ...AggregateFunc) *SigningCommitmentSelect {
	scs.fns = append(scs.fns, fns...)
	return scs
}

// Scan applies the selector query and scans the result into the given value.
func (scs *SigningCommitmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scs.ctx, ent.OpQuerySelect)
	if err := scs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SigningCommitmentQuery, *SigningCommitmentSelect](ctx, scs.SigningCommitmentQuery, scs, scs.inters, v)
}

func (scs *SigningCommitmentSelect) sqlScan(ctx context.Context, root *SigningCommitmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scs.fns))
	for _, fn := range scs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (scs *SigningCommitmentSelect) Modify(modifiers ...func(s *sql.Selector)) *SigningCommitmentSelect {
	scs.modifiers = append(scs.modifiers, modifiers...)
	return scs
}
