// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/sparkinvoice"
	"github.com/lightsparkdev/spark/so/ent/tokentransaction"
	"github.com/lightsparkdev/spark/so/ent/transfer"
)

// SparkInvoiceQuery is the builder for querying SparkInvoice entities.
type SparkInvoiceQuery struct {
	config
	ctx                  *QueryContext
	order                []sparkinvoice.OrderOption
	inters               []Interceptor
	predicates           []predicate.SparkInvoice
	withTokenTransaction *TokenTransactionQuery
	withTransfer         *TransferQuery
	modifiers            []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SparkInvoiceQuery builder.
func (siq *SparkInvoiceQuery) Where(ps ...predicate.SparkInvoice) *SparkInvoiceQuery {
	siq.predicates = append(siq.predicates, ps...)
	return siq
}

// Limit the number of records to be returned by this query.
func (siq *SparkInvoiceQuery) Limit(limit int) *SparkInvoiceQuery {
	siq.ctx.Limit = &limit
	return siq
}

// Offset to start from.
func (siq *SparkInvoiceQuery) Offset(offset int) *SparkInvoiceQuery {
	siq.ctx.Offset = &offset
	return siq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (siq *SparkInvoiceQuery) Unique(unique bool) *SparkInvoiceQuery {
	siq.ctx.Unique = &unique
	return siq
}

// Order specifies how the records should be ordered.
func (siq *SparkInvoiceQuery) Order(o ...sparkinvoice.OrderOption) *SparkInvoiceQuery {
	siq.order = append(siq.order, o...)
	return siq
}

// QueryTokenTransaction chains the current query on the "token_transaction" edge.
func (siq *SparkInvoiceQuery) QueryTokenTransaction() *TokenTransactionQuery {
	query := (&TokenTransactionClient{config: siq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := siq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := siq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sparkinvoice.Table, sparkinvoice.FieldID, selector),
			sqlgraph.To(tokentransaction.Table, tokentransaction.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, sparkinvoice.TokenTransactionTable, sparkinvoice.TokenTransactionPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(siq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTransfer chains the current query on the "transfer" edge.
func (siq *SparkInvoiceQuery) QueryTransfer() *TransferQuery {
	query := (&TransferClient{config: siq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := siq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := siq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sparkinvoice.Table, sparkinvoice.FieldID, selector),
			sqlgraph.To(transfer.Table, transfer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sparkinvoice.TransferTable, sparkinvoice.TransferColumn),
		)
		fromU = sqlgraph.SetNeighbors(siq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SparkInvoice entity from the query.
// Returns a *NotFoundError when no SparkInvoice was found.
func (siq *SparkInvoiceQuery) First(ctx context.Context) (*SparkInvoice, error) {
	nodes, err := siq.Limit(1).All(setContextOp(ctx, siq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sparkinvoice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (siq *SparkInvoiceQuery) FirstX(ctx context.Context) *SparkInvoice {
	node, err := siq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SparkInvoice ID from the query.
// Returns a *NotFoundError when no SparkInvoice ID was found.
func (siq *SparkInvoiceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = siq.Limit(1).IDs(setContextOp(ctx, siq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sparkinvoice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (siq *SparkInvoiceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := siq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SparkInvoice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SparkInvoice entity is found.
// Returns a *NotFoundError when no SparkInvoice entities are found.
func (siq *SparkInvoiceQuery) Only(ctx context.Context) (*SparkInvoice, error) {
	nodes, err := siq.Limit(2).All(setContextOp(ctx, siq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sparkinvoice.Label}
	default:
		return nil, &NotSingularError{sparkinvoice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (siq *SparkInvoiceQuery) OnlyX(ctx context.Context) *SparkInvoice {
	node, err := siq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SparkInvoice ID in the query.
// Returns a *NotSingularError when more than one SparkInvoice ID is found.
// Returns a *NotFoundError when no entities are found.
func (siq *SparkInvoiceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = siq.Limit(2).IDs(setContextOp(ctx, siq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sparkinvoice.Label}
	default:
		err = &NotSingularError{sparkinvoice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (siq *SparkInvoiceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := siq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SparkInvoices.
func (siq *SparkInvoiceQuery) All(ctx context.Context) ([]*SparkInvoice, error) {
	ctx = setContextOp(ctx, siq.ctx, ent.OpQueryAll)
	if err := siq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SparkInvoice, *SparkInvoiceQuery]()
	return withInterceptors[[]*SparkInvoice](ctx, siq, qr, siq.inters)
}

// AllX is like All, but panics if an error occurs.
func (siq *SparkInvoiceQuery) AllX(ctx context.Context) []*SparkInvoice {
	nodes, err := siq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SparkInvoice IDs.
func (siq *SparkInvoiceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if siq.ctx.Unique == nil && siq.path != nil {
		siq.Unique(true)
	}
	ctx = setContextOp(ctx, siq.ctx, ent.OpQueryIDs)
	if err = siq.Select(sparkinvoice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (siq *SparkInvoiceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := siq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (siq *SparkInvoiceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, siq.ctx, ent.OpQueryCount)
	if err := siq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, siq, querierCount[*SparkInvoiceQuery](), siq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (siq *SparkInvoiceQuery) CountX(ctx context.Context) int {
	count, err := siq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (siq *SparkInvoiceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, siq.ctx, ent.OpQueryExist)
	switch _, err := siq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (siq *SparkInvoiceQuery) ExistX(ctx context.Context) bool {
	exist, err := siq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SparkInvoiceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (siq *SparkInvoiceQuery) Clone() *SparkInvoiceQuery {
	if siq == nil {
		return nil
	}
	return &SparkInvoiceQuery{
		config:               siq.config,
		ctx:                  siq.ctx.Clone(),
		order:                append([]sparkinvoice.OrderOption{}, siq.order...),
		inters:               append([]Interceptor{}, siq.inters...),
		predicates:           append([]predicate.SparkInvoice{}, siq.predicates...),
		withTokenTransaction: siq.withTokenTransaction.Clone(),
		withTransfer:         siq.withTransfer.Clone(),
		// clone intermediate query.
		sql:       siq.sql.Clone(),
		path:      siq.path,
		modifiers: append([]func(*sql.Selector){}, siq.modifiers...),
	}
}

// WithTokenTransaction tells the query-builder to eager-load the nodes that are connected to
// the "token_transaction" edge. The optional arguments are used to configure the query builder of the edge.
func (siq *SparkInvoiceQuery) WithTokenTransaction(opts ...func(*TokenTransactionQuery)) *SparkInvoiceQuery {
	query := (&TokenTransactionClient{config: siq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	siq.withTokenTransaction = query
	return siq
}

// WithTransfer tells the query-builder to eager-load the nodes that are connected to
// the "transfer" edge. The optional arguments are used to configure the query builder of the edge.
func (siq *SparkInvoiceQuery) WithTransfer(opts ...func(*TransferQuery)) *SparkInvoiceQuery {
	query := (&TransferClient{config: siq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	siq.withTransfer = query
	return siq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SparkInvoice.Query().
//		GroupBy(sparkinvoice.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (siq *SparkInvoiceQuery) GroupBy(field string, fields ...string) *SparkInvoiceGroupBy {
	siq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SparkInvoiceGroupBy{build: siq}
	grbuild.flds = &siq.ctx.Fields
	grbuild.label = sparkinvoice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.SparkInvoice.Query().
//		Select(sparkinvoice.FieldCreateTime).
//		Scan(ctx, &v)
func (siq *SparkInvoiceQuery) Select(fields ...string) *SparkInvoiceSelect {
	siq.ctx.Fields = append(siq.ctx.Fields, fields...)
	sbuild := &SparkInvoiceSelect{SparkInvoiceQuery: siq}
	sbuild.label = sparkinvoice.Label
	sbuild.flds, sbuild.scan = &siq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SparkInvoiceSelect configured with the given aggregations.
func (siq *SparkInvoiceQuery) Aggregate(fns ...AggregateFunc) *SparkInvoiceSelect {
	return siq.Select().Aggregate(fns...)
}

func (siq *SparkInvoiceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range siq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, siq); err != nil {
				return err
			}
		}
	}
	for _, f := range siq.ctx.Fields {
		if !sparkinvoice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if siq.path != nil {
		prev, err := siq.path(ctx)
		if err != nil {
			return err
		}
		siq.sql = prev
	}
	return nil
}

func (siq *SparkInvoiceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SparkInvoice, error) {
	var (
		nodes       = []*SparkInvoice{}
		_spec       = siq.querySpec()
		loadedTypes = [2]bool{
			siq.withTokenTransaction != nil,
			siq.withTransfer != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SparkInvoice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SparkInvoice{config: siq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(siq.modifiers) > 0 {
		_spec.Modifiers = siq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, siq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := siq.withTokenTransaction; query != nil {
		if err := siq.loadTokenTransaction(ctx, query, nodes,
			func(n *SparkInvoice) { n.Edges.TokenTransaction = []*TokenTransaction{} },
			func(n *SparkInvoice, e *TokenTransaction) {
				n.Edges.TokenTransaction = append(n.Edges.TokenTransaction, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := siq.withTransfer; query != nil {
		if err := siq.loadTransfer(ctx, query, nodes,
			func(n *SparkInvoice) { n.Edges.Transfer = []*Transfer{} },
			func(n *SparkInvoice, e *Transfer) { n.Edges.Transfer = append(n.Edges.Transfer, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (siq *SparkInvoiceQuery) loadTokenTransaction(ctx context.Context, query *TokenTransactionQuery, nodes []*SparkInvoice, init func(*SparkInvoice), assign func(*SparkInvoice, *TokenTransaction)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*SparkInvoice)
	nids := make(map[uuid.UUID]map[*SparkInvoice]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(sparkinvoice.TokenTransactionTable)
		s.Join(joinT).On(s.C(tokentransaction.FieldID), joinT.C(sparkinvoice.TokenTransactionPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(sparkinvoice.TokenTransactionPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(sparkinvoice.TokenTransactionPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*SparkInvoice]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*TokenTransaction](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "token_transaction" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (siq *SparkInvoiceQuery) loadTransfer(ctx context.Context, query *TransferQuery, nodes []*SparkInvoice, init func(*SparkInvoice), assign func(*SparkInvoice, *Transfer)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*SparkInvoice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(transfer.FieldSparkInvoiceID)
	}
	query.Where(predicate.Transfer(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(sparkinvoice.TransferColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SparkInvoiceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "spark_invoice_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (siq *SparkInvoiceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := siq.querySpec()
	if len(siq.modifiers) > 0 {
		_spec.Modifiers = siq.modifiers
	}
	_spec.Node.Columns = siq.ctx.Fields
	if len(siq.ctx.Fields) > 0 {
		_spec.Unique = siq.ctx.Unique != nil && *siq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, siq.driver, _spec)
}

func (siq *SparkInvoiceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sparkinvoice.Table, sparkinvoice.Columns, sqlgraph.NewFieldSpec(sparkinvoice.FieldID, field.TypeUUID))
	_spec.From = siq.sql
	if unique := siq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if siq.path != nil {
		_spec.Unique = true
	}
	if fields := siq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sparkinvoice.FieldID)
		for i := range fields {
			if fields[i] != sparkinvoice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := siq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := siq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := siq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := siq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (siq *SparkInvoiceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(siq.driver.Dialect())
	t1 := builder.Table(sparkinvoice.Table)
	columns := siq.ctx.Fields
	if len(columns) == 0 {
		columns = sparkinvoice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if siq.sql != nil {
		selector = siq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if siq.ctx.Unique != nil && *siq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range siq.modifiers {
		m(selector)
	}
	for _, p := range siq.predicates {
		p(selector)
	}
	for _, p := range siq.order {
		p(selector)
	}
	if offset := siq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := siq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (siq *SparkInvoiceQuery) ForUpdate(opts ...sql.LockOption) *SparkInvoiceQuery {
	if siq.driver.Dialect() == dialect.Postgres {
		siq.Unique(false)
	}
	siq.modifiers = append(siq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return siq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (siq *SparkInvoiceQuery) ForShare(opts ...sql.LockOption) *SparkInvoiceQuery {
	if siq.driver.Dialect() == dialect.Postgres {
		siq.Unique(false)
	}
	siq.modifiers = append(siq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return siq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (siq *SparkInvoiceQuery) Modify(modifiers ...func(s *sql.Selector)) *SparkInvoiceSelect {
	siq.modifiers = append(siq.modifiers, modifiers...)
	return siq.Select()
}

// SparkInvoiceGroupBy is the group-by builder for SparkInvoice entities.
type SparkInvoiceGroupBy struct {
	selector
	build *SparkInvoiceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sigb *SparkInvoiceGroupBy) Aggregate(fns ...AggregateFunc) *SparkInvoiceGroupBy {
	sigb.fns = append(sigb.fns, fns...)
	return sigb
}

// Scan applies the selector query and scans the result into the given value.
func (sigb *SparkInvoiceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sigb.build.ctx, ent.OpQueryGroupBy)
	if err := sigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SparkInvoiceQuery, *SparkInvoiceGroupBy](ctx, sigb.build, sigb, sigb.build.inters, v)
}

func (sigb *SparkInvoiceGroupBy) sqlScan(ctx context.Context, root *SparkInvoiceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sigb.fns))
	for _, fn := range sigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sigb.flds)+len(sigb.fns))
		for _, f := range *sigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SparkInvoiceSelect is the builder for selecting fields of SparkInvoice entities.
type SparkInvoiceSelect struct {
	*SparkInvoiceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sis *SparkInvoiceSelect) Aggregate(fns ...AggregateFunc) *SparkInvoiceSelect {
	sis.fns = append(sis.fns, fns...)
	return sis
}

// Scan applies the selector query and scans the result into the given value.
func (sis *SparkInvoiceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sis.ctx, ent.OpQuerySelect)
	if err := sis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SparkInvoiceQuery, *SparkInvoiceSelect](ctx, sis.SparkInvoiceQuery, sis, sis.inters, v)
}

func (sis *SparkInvoiceSelect) sqlScan(ctx context.Context, root *SparkInvoiceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sis.fns))
	for _, fn := range sis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sis *SparkInvoiceSelect) Modify(modifiers ...func(s *sql.Selector)) *SparkInvoiceSelect {
	sis.modifiers = append(sis.modifiers, modifiers...)
	return sis
}
