// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
	"github.com/lightsparkdev/spark/so/ent/tokenpartialrevocationsecretshare"
)

// TokenPartialRevocationSecretShareQuery is the builder for querying TokenPartialRevocationSecretShare entities.
type TokenPartialRevocationSecretShareQuery struct {
	config
	ctx             *QueryContext
	order           []tokenpartialrevocationsecretshare.OrderOption
	inters          []Interceptor
	predicates      []predicate.TokenPartialRevocationSecretShare
	withTokenOutput *TokenOutputQuery
	withFKs         bool
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TokenPartialRevocationSecretShareQuery builder.
func (tprssq *TokenPartialRevocationSecretShareQuery) Where(ps ...predicate.TokenPartialRevocationSecretShare) *TokenPartialRevocationSecretShareQuery {
	tprssq.predicates = append(tprssq.predicates, ps...)
	return tprssq
}

// Limit the number of records to be returned by this query.
func (tprssq *TokenPartialRevocationSecretShareQuery) Limit(limit int) *TokenPartialRevocationSecretShareQuery {
	tprssq.ctx.Limit = &limit
	return tprssq
}

// Offset to start from.
func (tprssq *TokenPartialRevocationSecretShareQuery) Offset(offset int) *TokenPartialRevocationSecretShareQuery {
	tprssq.ctx.Offset = &offset
	return tprssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tprssq *TokenPartialRevocationSecretShareQuery) Unique(unique bool) *TokenPartialRevocationSecretShareQuery {
	tprssq.ctx.Unique = &unique
	return tprssq
}

// Order specifies how the records should be ordered.
func (tprssq *TokenPartialRevocationSecretShareQuery) Order(o ...tokenpartialrevocationsecretshare.OrderOption) *TokenPartialRevocationSecretShareQuery {
	tprssq.order = append(tprssq.order, o...)
	return tprssq
}

// QueryTokenOutput chains the current query on the "token_output" edge.
func (tprssq *TokenPartialRevocationSecretShareQuery) QueryTokenOutput() *TokenOutputQuery {
	query := (&TokenOutputClient{config: tprssq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tprssq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tprssq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokenpartialrevocationsecretshare.Table, tokenpartialrevocationsecretshare.FieldID, selector),
			sqlgraph.To(tokenoutput.Table, tokenoutput.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tokenpartialrevocationsecretshare.TokenOutputTable, tokenpartialrevocationsecretshare.TokenOutputColumn),
		)
		fromU = sqlgraph.SetNeighbors(tprssq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TokenPartialRevocationSecretShare entity from the query.
// Returns a *NotFoundError when no TokenPartialRevocationSecretShare was found.
func (tprssq *TokenPartialRevocationSecretShareQuery) First(ctx context.Context) (*TokenPartialRevocationSecretShare, error) {
	nodes, err := tprssq.Limit(1).All(setContextOp(ctx, tprssq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tokenpartialrevocationsecretshare.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tprssq *TokenPartialRevocationSecretShareQuery) FirstX(ctx context.Context) *TokenPartialRevocationSecretShare {
	node, err := tprssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TokenPartialRevocationSecretShare ID from the query.
// Returns a *NotFoundError when no TokenPartialRevocationSecretShare ID was found.
func (tprssq *TokenPartialRevocationSecretShareQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tprssq.Limit(1).IDs(setContextOp(ctx, tprssq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tokenpartialrevocationsecretshare.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tprssq *TokenPartialRevocationSecretShareQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tprssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TokenPartialRevocationSecretShare entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TokenPartialRevocationSecretShare entity is found.
// Returns a *NotFoundError when no TokenPartialRevocationSecretShare entities are found.
func (tprssq *TokenPartialRevocationSecretShareQuery) Only(ctx context.Context) (*TokenPartialRevocationSecretShare, error) {
	nodes, err := tprssq.Limit(2).All(setContextOp(ctx, tprssq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tokenpartialrevocationsecretshare.Label}
	default:
		return nil, &NotSingularError{tokenpartialrevocationsecretshare.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tprssq *TokenPartialRevocationSecretShareQuery) OnlyX(ctx context.Context) *TokenPartialRevocationSecretShare {
	node, err := tprssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TokenPartialRevocationSecretShare ID in the query.
// Returns a *NotSingularError when more than one TokenPartialRevocationSecretShare ID is found.
// Returns a *NotFoundError when no entities are found.
func (tprssq *TokenPartialRevocationSecretShareQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tprssq.Limit(2).IDs(setContextOp(ctx, tprssq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tokenpartialrevocationsecretshare.Label}
	default:
		err = &NotSingularError{tokenpartialrevocationsecretshare.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tprssq *TokenPartialRevocationSecretShareQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tprssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TokenPartialRevocationSecretShares.
func (tprssq *TokenPartialRevocationSecretShareQuery) All(ctx context.Context) ([]*TokenPartialRevocationSecretShare, error) {
	ctx = setContextOp(ctx, tprssq.ctx, ent.OpQueryAll)
	if err := tprssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TokenPartialRevocationSecretShare, *TokenPartialRevocationSecretShareQuery]()
	return withInterceptors[[]*TokenPartialRevocationSecretShare](ctx, tprssq, qr, tprssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tprssq *TokenPartialRevocationSecretShareQuery) AllX(ctx context.Context) []*TokenPartialRevocationSecretShare {
	nodes, err := tprssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TokenPartialRevocationSecretShare IDs.
func (tprssq *TokenPartialRevocationSecretShareQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tprssq.ctx.Unique == nil && tprssq.path != nil {
		tprssq.Unique(true)
	}
	ctx = setContextOp(ctx, tprssq.ctx, ent.OpQueryIDs)
	if err = tprssq.Select(tokenpartialrevocationsecretshare.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tprssq *TokenPartialRevocationSecretShareQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tprssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tprssq *TokenPartialRevocationSecretShareQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tprssq.ctx, ent.OpQueryCount)
	if err := tprssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tprssq, querierCount[*TokenPartialRevocationSecretShareQuery](), tprssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tprssq *TokenPartialRevocationSecretShareQuery) CountX(ctx context.Context) int {
	count, err := tprssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tprssq *TokenPartialRevocationSecretShareQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tprssq.ctx, ent.OpQueryExist)
	switch _, err := tprssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tprssq *TokenPartialRevocationSecretShareQuery) ExistX(ctx context.Context) bool {
	exist, err := tprssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TokenPartialRevocationSecretShareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tprssq *TokenPartialRevocationSecretShareQuery) Clone() *TokenPartialRevocationSecretShareQuery {
	if tprssq == nil {
		return nil
	}
	return &TokenPartialRevocationSecretShareQuery{
		config:          tprssq.config,
		ctx:             tprssq.ctx.Clone(),
		order:           append([]tokenpartialrevocationsecretshare.OrderOption{}, tprssq.order...),
		inters:          append([]Interceptor{}, tprssq.inters...),
		predicates:      append([]predicate.TokenPartialRevocationSecretShare{}, tprssq.predicates...),
		withTokenOutput: tprssq.withTokenOutput.Clone(),
		// clone intermediate query.
		sql:       tprssq.sql.Clone(),
		path:      tprssq.path,
		modifiers: append([]func(*sql.Selector){}, tprssq.modifiers...),
	}
}

// WithTokenOutput tells the query-builder to eager-load the nodes that are connected to
// the "token_output" edge. The optional arguments are used to configure the query builder of the edge.
func (tprssq *TokenPartialRevocationSecretShareQuery) WithTokenOutput(opts ...func(*TokenOutputQuery)) *TokenPartialRevocationSecretShareQuery {
	query := (&TokenOutputClient{config: tprssq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tprssq.withTokenOutput = query
	return tprssq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TokenPartialRevocationSecretShare.Query().
//		GroupBy(tokenpartialrevocationsecretshare.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tprssq *TokenPartialRevocationSecretShareQuery) GroupBy(field string, fields ...string) *TokenPartialRevocationSecretShareGroupBy {
	tprssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TokenPartialRevocationSecretShareGroupBy{build: tprssq}
	grbuild.flds = &tprssq.ctx.Fields
	grbuild.label = tokenpartialrevocationsecretshare.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TokenPartialRevocationSecretShare.Query().
//		Select(tokenpartialrevocationsecretshare.FieldCreateTime).
//		Scan(ctx, &v)
func (tprssq *TokenPartialRevocationSecretShareQuery) Select(fields ...string) *TokenPartialRevocationSecretShareSelect {
	tprssq.ctx.Fields = append(tprssq.ctx.Fields, fields...)
	sbuild := &TokenPartialRevocationSecretShareSelect{TokenPartialRevocationSecretShareQuery: tprssq}
	sbuild.label = tokenpartialrevocationsecretshare.Label
	sbuild.flds, sbuild.scan = &tprssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TokenPartialRevocationSecretShareSelect configured with the given aggregations.
func (tprssq *TokenPartialRevocationSecretShareQuery) Aggregate(fns ...AggregateFunc) *TokenPartialRevocationSecretShareSelect {
	return tprssq.Select().Aggregate(fns...)
}

func (tprssq *TokenPartialRevocationSecretShareQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tprssq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tprssq); err != nil {
				return err
			}
		}
	}
	for _, f := range tprssq.ctx.Fields {
		if !tokenpartialrevocationsecretshare.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tprssq.path != nil {
		prev, err := tprssq.path(ctx)
		if err != nil {
			return err
		}
		tprssq.sql = prev
	}
	return nil
}

func (tprssq *TokenPartialRevocationSecretShareQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TokenPartialRevocationSecretShare, error) {
	var (
		nodes       = []*TokenPartialRevocationSecretShare{}
		withFKs     = tprssq.withFKs
		_spec       = tprssq.querySpec()
		loadedTypes = [1]bool{
			tprssq.withTokenOutput != nil,
		}
	)
	if tprssq.withTokenOutput != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tokenpartialrevocationsecretshare.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TokenPartialRevocationSecretShare).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TokenPartialRevocationSecretShare{config: tprssq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tprssq.modifiers) > 0 {
		_spec.Modifiers = tprssq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tprssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tprssq.withTokenOutput; query != nil {
		if err := tprssq.loadTokenOutput(ctx, query, nodes, nil,
			func(n *TokenPartialRevocationSecretShare, e *TokenOutput) { n.Edges.TokenOutput = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tprssq *TokenPartialRevocationSecretShareQuery) loadTokenOutput(ctx context.Context, query *TokenOutputQuery, nodes []*TokenPartialRevocationSecretShare, init func(*TokenPartialRevocationSecretShare), assign func(*TokenPartialRevocationSecretShare, *TokenOutput)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TokenPartialRevocationSecretShare)
	for i := range nodes {
		if nodes[i].token_output_token_partial_revocation_secret_shares == nil {
			continue
		}
		fk := *nodes[i].token_output_token_partial_revocation_secret_shares
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tokenoutput.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_output_token_partial_revocation_secret_shares" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tprssq *TokenPartialRevocationSecretShareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tprssq.querySpec()
	if len(tprssq.modifiers) > 0 {
		_spec.Modifiers = tprssq.modifiers
	}
	_spec.Node.Columns = tprssq.ctx.Fields
	if len(tprssq.ctx.Fields) > 0 {
		_spec.Unique = tprssq.ctx.Unique != nil && *tprssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tprssq.driver, _spec)
}

func (tprssq *TokenPartialRevocationSecretShareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tokenpartialrevocationsecretshare.Table, tokenpartialrevocationsecretshare.Columns, sqlgraph.NewFieldSpec(tokenpartialrevocationsecretshare.FieldID, field.TypeUUID))
	_spec.From = tprssq.sql
	if unique := tprssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tprssq.path != nil {
		_spec.Unique = true
	}
	if fields := tprssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenpartialrevocationsecretshare.FieldID)
		for i := range fields {
			if fields[i] != tokenpartialrevocationsecretshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tprssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tprssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tprssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tprssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tprssq *TokenPartialRevocationSecretShareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tprssq.driver.Dialect())
	t1 := builder.Table(tokenpartialrevocationsecretshare.Table)
	columns := tprssq.ctx.Fields
	if len(columns) == 0 {
		columns = tokenpartialrevocationsecretshare.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tprssq.sql != nil {
		selector = tprssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tprssq.ctx.Unique != nil && *tprssq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tprssq.modifiers {
		m(selector)
	}
	for _, p := range tprssq.predicates {
		p(selector)
	}
	for _, p := range tprssq.order {
		p(selector)
	}
	if offset := tprssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tprssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (tprssq *TokenPartialRevocationSecretShareQuery) ForUpdate(opts ...sql.LockOption) *TokenPartialRevocationSecretShareQuery {
	if tprssq.driver.Dialect() == dialect.Postgres {
		tprssq.Unique(false)
	}
	tprssq.modifiers = append(tprssq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return tprssq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (tprssq *TokenPartialRevocationSecretShareQuery) ForShare(opts ...sql.LockOption) *TokenPartialRevocationSecretShareQuery {
	if tprssq.driver.Dialect() == dialect.Postgres {
		tprssq.Unique(false)
	}
	tprssq.modifiers = append(tprssq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return tprssq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tprssq *TokenPartialRevocationSecretShareQuery) Modify(modifiers ...func(s *sql.Selector)) *TokenPartialRevocationSecretShareSelect {
	tprssq.modifiers = append(tprssq.modifiers, modifiers...)
	return tprssq.Select()
}

// TokenPartialRevocationSecretShareGroupBy is the group-by builder for TokenPartialRevocationSecretShare entities.
type TokenPartialRevocationSecretShareGroupBy struct {
	selector
	build *TokenPartialRevocationSecretShareQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tprssgb *TokenPartialRevocationSecretShareGroupBy) Aggregate(fns ...AggregateFunc) *TokenPartialRevocationSecretShareGroupBy {
	tprssgb.fns = append(tprssgb.fns, fns...)
	return tprssgb
}

// Scan applies the selector query and scans the result into the given value.
func (tprssgb *TokenPartialRevocationSecretShareGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tprssgb.build.ctx, ent.OpQueryGroupBy)
	if err := tprssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenPartialRevocationSecretShareQuery, *TokenPartialRevocationSecretShareGroupBy](ctx, tprssgb.build, tprssgb, tprssgb.build.inters, v)
}

func (tprssgb *TokenPartialRevocationSecretShareGroupBy) sqlScan(ctx context.Context, root *TokenPartialRevocationSecretShareQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tprssgb.fns))
	for _, fn := range tprssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tprssgb.flds)+len(tprssgb.fns))
		for _, f := range *tprssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tprssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tprssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TokenPartialRevocationSecretShareSelect is the builder for selecting fields of TokenPartialRevocationSecretShare entities.
type TokenPartialRevocationSecretShareSelect struct {
	*TokenPartialRevocationSecretShareQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tprsss *TokenPartialRevocationSecretShareSelect) Aggregate(fns ...AggregateFunc) *TokenPartialRevocationSecretShareSelect {
	tprsss.fns = append(tprsss.fns, fns...)
	return tprsss
}

// Scan applies the selector query and scans the result into the given value.
func (tprsss *TokenPartialRevocationSecretShareSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tprsss.ctx, ent.OpQuerySelect)
	if err := tprsss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenPartialRevocationSecretShareQuery, *TokenPartialRevocationSecretShareSelect](ctx, tprsss.TokenPartialRevocationSecretShareQuery, tprsss, tprsss.inters, v)
}

func (tprsss *TokenPartialRevocationSecretShareSelect) sqlScan(ctx context.Context, root *TokenPartialRevocationSecretShareQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tprsss.fns))
	for _, fn := range tprsss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tprsss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tprsss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tprsss *TokenPartialRevocationSecretShareSelect) Modify(modifiers ...func(s *sql.Selector)) *TokenPartialRevocationSecretShareSelect {
	tprsss.modifiers = append(tprsss.modifiers, modifiers...)
	return tprsss
}
