// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/l1tokencreate"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokencreate"
	"github.com/lightsparkdev/spark/so/ent/tokenfreeze"
	"github.com/lightsparkdev/spark/so/ent/tokenoutput"
	"github.com/lightsparkdev/spark/so/ent/tokentransaction"
)

// TokenCreateQuery is the builder for querying TokenCreate entities.
type TokenCreateQuery struct {
	config
	ctx                  *QueryContext
	order                []tokencreate.OrderOption
	inters               []Interceptor
	predicates           []predicate.TokenCreate
	withTokenTransaction *TokenTransactionQuery
	withL1TokenCreate    *L1TokenCreateQuery
	withTokenOutput      *TokenOutputQuery
	withTokenFreeze      *TokenFreezeQuery
	withFKs              bool
	modifiers            []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TokenCreateQuery builder.
func (tcq *TokenCreateQuery) Where(ps ...predicate.TokenCreate) *TokenCreateQuery {
	tcq.predicates = append(tcq.predicates, ps...)
	return tcq
}

// Limit the number of records to be returned by this query.
func (tcq *TokenCreateQuery) Limit(limit int) *TokenCreateQuery {
	tcq.ctx.Limit = &limit
	return tcq
}

// Offset to start from.
func (tcq *TokenCreateQuery) Offset(offset int) *TokenCreateQuery {
	tcq.ctx.Offset = &offset
	return tcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tcq *TokenCreateQuery) Unique(unique bool) *TokenCreateQuery {
	tcq.ctx.Unique = &unique
	return tcq
}

// Order specifies how the records should be ordered.
func (tcq *TokenCreateQuery) Order(o ...tokencreate.OrderOption) *TokenCreateQuery {
	tcq.order = append(tcq.order, o...)
	return tcq
}

// QueryTokenTransaction chains the current query on the "token_transaction" edge.
func (tcq *TokenCreateQuery) QueryTokenTransaction() *TokenTransactionQuery {
	query := (&TokenTransactionClient{config: tcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokencreate.Table, tokencreate.FieldID, selector),
			sqlgraph.To(tokentransaction.Table, tokentransaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, tokencreate.TokenTransactionTable, tokencreate.TokenTransactionColumn),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryL1TokenCreate chains the current query on the "l1_token_create" edge.
func (tcq *TokenCreateQuery) QueryL1TokenCreate() *L1TokenCreateQuery {
	query := (&L1TokenCreateClient{config: tcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokencreate.Table, tokencreate.FieldID, selector),
			sqlgraph.To(l1tokencreate.Table, l1tokencreate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tokencreate.L1TokenCreateTable, tokencreate.L1TokenCreateColumn),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTokenOutput chains the current query on the "token_output" edge.
func (tcq *TokenCreateQuery) QueryTokenOutput() *TokenOutputQuery {
	query := (&TokenOutputClient{config: tcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokencreate.Table, tokencreate.FieldID, selector),
			sqlgraph.To(tokenoutput.Table, tokenoutput.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tokencreate.TokenOutputTable, tokencreate.TokenOutputColumn),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTokenFreeze chains the current query on the "token_freeze" edge.
func (tcq *TokenCreateQuery) QueryTokenFreeze() *TokenFreezeQuery {
	query := (&TokenFreezeClient{config: tcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokencreate.Table, tokencreate.FieldID, selector),
			sqlgraph.To(tokenfreeze.Table, tokenfreeze.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tokencreate.TokenFreezeTable, tokencreate.TokenFreezeColumn),
		)
		fromU = sqlgraph.SetNeighbors(tcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TokenCreate entity from the query.
// Returns a *NotFoundError when no TokenCreate was found.
func (tcq *TokenCreateQuery) First(ctx context.Context) (*TokenCreate, error) {
	nodes, err := tcq.Limit(1).All(setContextOp(ctx, tcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tokencreate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tcq *TokenCreateQuery) FirstX(ctx context.Context) *TokenCreate {
	node, err := tcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TokenCreate ID from the query.
// Returns a *NotFoundError when no TokenCreate ID was found.
func (tcq *TokenCreateQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tcq.Limit(1).IDs(setContextOp(ctx, tcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tokencreate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tcq *TokenCreateQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TokenCreate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TokenCreate entity is found.
// Returns a *NotFoundError when no TokenCreate entities are found.
func (tcq *TokenCreateQuery) Only(ctx context.Context) (*TokenCreate, error) {
	nodes, err := tcq.Limit(2).All(setContextOp(ctx, tcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tokencreate.Label}
	default:
		return nil, &NotSingularError{tokencreate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tcq *TokenCreateQuery) OnlyX(ctx context.Context) *TokenCreate {
	node, err := tcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TokenCreate ID in the query.
// Returns a *NotSingularError when more than one TokenCreate ID is found.
// Returns a *NotFoundError when no entities are found.
func (tcq *TokenCreateQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tcq.Limit(2).IDs(setContextOp(ctx, tcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tokencreate.Label}
	default:
		err = &NotSingularError{tokencreate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tcq *TokenCreateQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TokenCreates.
func (tcq *TokenCreateQuery) All(ctx context.Context) ([]*TokenCreate, error) {
	ctx = setContextOp(ctx, tcq.ctx, ent.OpQueryAll)
	if err := tcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TokenCreate, *TokenCreateQuery]()
	return withInterceptors[[]*TokenCreate](ctx, tcq, qr, tcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tcq *TokenCreateQuery) AllX(ctx context.Context) []*TokenCreate {
	nodes, err := tcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TokenCreate IDs.
func (tcq *TokenCreateQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tcq.ctx.Unique == nil && tcq.path != nil {
		tcq.Unique(true)
	}
	ctx = setContextOp(ctx, tcq.ctx, ent.OpQueryIDs)
	if err = tcq.Select(tokencreate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tcq *TokenCreateQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tcq *TokenCreateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tcq.ctx, ent.OpQueryCount)
	if err := tcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tcq, querierCount[*TokenCreateQuery](), tcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tcq *TokenCreateQuery) CountX(ctx context.Context) int {
	count, err := tcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tcq *TokenCreateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tcq.ctx, ent.OpQueryExist)
	switch _, err := tcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tcq *TokenCreateQuery) ExistX(ctx context.Context) bool {
	exist, err := tcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TokenCreateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tcq *TokenCreateQuery) Clone() *TokenCreateQuery {
	if tcq == nil {
		return nil
	}
	return &TokenCreateQuery{
		config:               tcq.config,
		ctx:                  tcq.ctx.Clone(),
		order:                append([]tokencreate.OrderOption{}, tcq.order...),
		inters:               append([]Interceptor{}, tcq.inters...),
		predicates:           append([]predicate.TokenCreate{}, tcq.predicates...),
		withTokenTransaction: tcq.withTokenTransaction.Clone(),
		withL1TokenCreate:    tcq.withL1TokenCreate.Clone(),
		withTokenOutput:      tcq.withTokenOutput.Clone(),
		withTokenFreeze:      tcq.withTokenFreeze.Clone(),
		// clone intermediate query.
		sql:       tcq.sql.Clone(),
		path:      tcq.path,
		modifiers: append([]func(*sql.Selector){}, tcq.modifiers...),
	}
}

// WithTokenTransaction tells the query-builder to eager-load the nodes that are connected to
// the "token_transaction" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TokenCreateQuery) WithTokenTransaction(opts ...func(*TokenTransactionQuery)) *TokenCreateQuery {
	query := (&TokenTransactionClient{config: tcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tcq.withTokenTransaction = query
	return tcq
}

// WithL1TokenCreate tells the query-builder to eager-load the nodes that are connected to
// the "l1_token_create" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TokenCreateQuery) WithL1TokenCreate(opts ...func(*L1TokenCreateQuery)) *TokenCreateQuery {
	query := (&L1TokenCreateClient{config: tcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tcq.withL1TokenCreate = query
	return tcq
}

// WithTokenOutput tells the query-builder to eager-load the nodes that are connected to
// the "token_output" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TokenCreateQuery) WithTokenOutput(opts ...func(*TokenOutputQuery)) *TokenCreateQuery {
	query := (&TokenOutputClient{config: tcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tcq.withTokenOutput = query
	return tcq
}

// WithTokenFreeze tells the query-builder to eager-load the nodes that are connected to
// the "token_freeze" edge. The optional arguments are used to configure the query builder of the edge.
func (tcq *TokenCreateQuery) WithTokenFreeze(opts ...func(*TokenFreezeQuery)) *TokenCreateQuery {
	query := (&TokenFreezeClient{config: tcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tcq.withTokenFreeze = query
	return tcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TokenCreate.Query().
//		GroupBy(tokencreate.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tcq *TokenCreateQuery) GroupBy(field string, fields ...string) *TokenCreateGroupBy {
	tcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TokenCreateGroupBy{build: tcq}
	grbuild.flds = &tcq.ctx.Fields
	grbuild.label = tokencreate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TokenCreate.Query().
//		Select(tokencreate.FieldCreateTime).
//		Scan(ctx, &v)
func (tcq *TokenCreateQuery) Select(fields ...string) *TokenCreateSelect {
	tcq.ctx.Fields = append(tcq.ctx.Fields, fields...)
	sbuild := &TokenCreateSelect{TokenCreateQuery: tcq}
	sbuild.label = tokencreate.Label
	sbuild.flds, sbuild.scan = &tcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TokenCreateSelect configured with the given aggregations.
func (tcq *TokenCreateQuery) Aggregate(fns ...AggregateFunc) *TokenCreateSelect {
	return tcq.Select().Aggregate(fns...)
}

func (tcq *TokenCreateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tcq); err != nil {
				return err
			}
		}
	}
	for _, f := range tcq.ctx.Fields {
		if !tokencreate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tcq.path != nil {
		prev, err := tcq.path(ctx)
		if err != nil {
			return err
		}
		tcq.sql = prev
	}
	return nil
}

func (tcq *TokenCreateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TokenCreate, error) {
	var (
		nodes       = []*TokenCreate{}
		withFKs     = tcq.withFKs
		_spec       = tcq.querySpec()
		loadedTypes = [4]bool{
			tcq.withTokenTransaction != nil,
			tcq.withL1TokenCreate != nil,
			tcq.withTokenOutput != nil,
			tcq.withTokenFreeze != nil,
		}
	)
	if tcq.withL1TokenCreate != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tokencreate.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TokenCreate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TokenCreate{config: tcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tcq.modifiers) > 0 {
		_spec.Modifiers = tcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tcq.withTokenTransaction; query != nil {
		if err := tcq.loadTokenTransaction(ctx, query, nodes,
			func(n *TokenCreate) { n.Edges.TokenTransaction = []*TokenTransaction{} },
			func(n *TokenCreate, e *TokenTransaction) {
				n.Edges.TokenTransaction = append(n.Edges.TokenTransaction, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := tcq.withL1TokenCreate; query != nil {
		if err := tcq.loadL1TokenCreate(ctx, query, nodes, nil,
			func(n *TokenCreate, e *L1TokenCreate) { n.Edges.L1TokenCreate = e }); err != nil {
			return nil, err
		}
	}
	if query := tcq.withTokenOutput; query != nil {
		if err := tcq.loadTokenOutput(ctx, query, nodes,
			func(n *TokenCreate) { n.Edges.TokenOutput = []*TokenOutput{} },
			func(n *TokenCreate, e *TokenOutput) { n.Edges.TokenOutput = append(n.Edges.TokenOutput, e) }); err != nil {
			return nil, err
		}
	}
	if query := tcq.withTokenFreeze; query != nil {
		if err := tcq.loadTokenFreeze(ctx, query, nodes,
			func(n *TokenCreate) { n.Edges.TokenFreeze = []*TokenFreeze{} },
			func(n *TokenCreate, e *TokenFreeze) { n.Edges.TokenFreeze = append(n.Edges.TokenFreeze, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tcq *TokenCreateQuery) loadTokenTransaction(ctx context.Context, query *TokenTransactionQuery, nodes []*TokenCreate, init func(*TokenCreate), assign func(*TokenCreate, *TokenTransaction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*TokenCreate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.TokenTransaction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tokencreate.TokenTransactionColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.token_transaction_create
		if fk == nil {
			return fmt.Errorf(`foreign-key "token_transaction_create" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "token_transaction_create" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (tcq *TokenCreateQuery) loadL1TokenCreate(ctx context.Context, query *L1TokenCreateQuery, nodes []*TokenCreate, init func(*TokenCreate), assign func(*TokenCreate, *L1TokenCreate)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TokenCreate)
	for i := range nodes {
		if nodes[i].token_create_l1_token_create == nil {
			continue
		}
		fk := *nodes[i].token_create_l1_token_create
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(l1tokencreate.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_create_l1_token_create" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tcq *TokenCreateQuery) loadTokenOutput(ctx context.Context, query *TokenOutputQuery, nodes []*TokenCreate, init func(*TokenCreate), assign func(*TokenCreate, *TokenOutput)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*TokenCreate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tokenoutput.FieldTokenCreateID)
	}
	query.Where(predicate.TokenOutput(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tokencreate.TokenOutputColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TokenCreateID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "token_create_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (tcq *TokenCreateQuery) loadTokenFreeze(ctx context.Context, query *TokenFreezeQuery, nodes []*TokenCreate, init func(*TokenCreate), assign func(*TokenCreate, *TokenFreeze)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*TokenCreate)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tokenfreeze.FieldTokenCreateID)
	}
	query.Where(predicate.TokenFreeze(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tokencreate.TokenFreezeColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TokenCreateID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "token_create_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tcq *TokenCreateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tcq.querySpec()
	if len(tcq.modifiers) > 0 {
		_spec.Modifiers = tcq.modifiers
	}
	_spec.Node.Columns = tcq.ctx.Fields
	if len(tcq.ctx.Fields) > 0 {
		_spec.Unique = tcq.ctx.Unique != nil && *tcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tcq.driver, _spec)
}

func (tcq *TokenCreateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tokencreate.Table, tokencreate.Columns, sqlgraph.NewFieldSpec(tokencreate.FieldID, field.TypeUUID))
	_spec.From = tcq.sql
	if unique := tcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tcq.path != nil {
		_spec.Unique = true
	}
	if fields := tcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokencreate.FieldID)
		for i := range fields {
			if fields[i] != tokencreate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tcq *TokenCreateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tcq.driver.Dialect())
	t1 := builder.Table(tokencreate.Table)
	columns := tcq.ctx.Fields
	if len(columns) == 0 {
		columns = tokencreate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tcq.sql != nil {
		selector = tcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tcq.ctx.Unique != nil && *tcq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tcq.modifiers {
		m(selector)
	}
	for _, p := range tcq.predicates {
		p(selector)
	}
	for _, p := range tcq.order {
		p(selector)
	}
	if offset := tcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (tcq *TokenCreateQuery) ForUpdate(opts ...sql.LockOption) *TokenCreateQuery {
	if tcq.driver.Dialect() == dialect.Postgres {
		tcq.Unique(false)
	}
	tcq.modifiers = append(tcq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return tcq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (tcq *TokenCreateQuery) ForShare(opts ...sql.LockOption) *TokenCreateQuery {
	if tcq.driver.Dialect() == dialect.Postgres {
		tcq.Unique(false)
	}
	tcq.modifiers = append(tcq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return tcq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tcq *TokenCreateQuery) Modify(modifiers ...func(s *sql.Selector)) *TokenCreateSelect {
	tcq.modifiers = append(tcq.modifiers, modifiers...)
	return tcq.Select()
}

// TokenCreateGroupBy is the group-by builder for TokenCreate entities.
type TokenCreateGroupBy struct {
	selector
	build *TokenCreateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tcgb *TokenCreateGroupBy) Aggregate(fns ...AggregateFunc) *TokenCreateGroupBy {
	tcgb.fns = append(tcgb.fns, fns...)
	return tcgb
}

// Scan applies the selector query and scans the result into the given value.
func (tcgb *TokenCreateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcgb.build.ctx, ent.OpQueryGroupBy)
	if err := tcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenCreateQuery, *TokenCreateGroupBy](ctx, tcgb.build, tcgb, tcgb.build.inters, v)
}

func (tcgb *TokenCreateGroupBy) sqlScan(ctx context.Context, root *TokenCreateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tcgb.fns))
	for _, fn := range tcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tcgb.flds)+len(tcgb.fns))
		for _, f := range *tcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TokenCreateSelect is the builder for selecting fields of TokenCreate entities.
type TokenCreateSelect struct {
	*TokenCreateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tcs *TokenCreateSelect) Aggregate(fns ...AggregateFunc) *TokenCreateSelect {
	tcs.fns = append(tcs.fns, fns...)
	return tcs
}

// Scan applies the selector query and scans the result into the given value.
func (tcs *TokenCreateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tcs.ctx, ent.OpQuerySelect)
	if err := tcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenCreateQuery, *TokenCreateSelect](ctx, tcs.TokenCreateQuery, tcs, tcs.inters, v)
}

func (tcs *TokenCreateSelect) sqlScan(ctx context.Context, root *TokenCreateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tcs.fns))
	for _, fn := range tcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tcs *TokenCreateSelect) Modify(modifiers ...func(s *sql.Selector)) *TokenCreateSelect {
	tcs.modifiers = append(tcs.modifiers, modifiers...)
	return tcs
}
